var DATA=window.PORTFOLIO_DATA||{"cover":{},"email":"","categories":[],"works":[]};
var catById=function(id){return DATA.categories.find(function(c){return c.id===id})};
var fw=[],lbIdx=-1,activeCat='all',searchQ='',activeRole=null,activeRoleCats=[],portfolioView='curation';
var USER_WORK_KEY='xiaokai_portfolio_user_works_v1',USER_WORKS=[],CURATE_KEY='xiaokai_portfolio_curated_ids_v1',CURATED_IDS=[],deckWorks=[],deckIndex=0;
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function videoPlaceholder(title){return 'assets/icons/video-placeholder.svg'}
function cardThumb(w){if(w.mediaType==='video')return w.thumbnail||videoPlaceholder(w.title);return w.mediaBase64||w.thumbnail||videoPlaceholder(w.title)}
function assetUrlForCss(src){if(!src||/^(data:|https?:|file:)/.test(src))return src;return new URL(src,location.href).href}
function uniqueWorks(list){var ids={},out=[];(list||[]).forEach(function(w){if(w&&w.id&&!ids[w.id]){ids[w.id]=1;out.push(w)}});return out}
function readEmbeddedWorks(){var data=window.PORTFOLIO_EMBEDDED_WORKS||[],works=Array.isArray(data)?data:data.works,out=Array.isArray(works)?works.slice():[],el=document.getElementById('portfolioEmbeddedWorks');if(el&&el.textContent.trim()){try{var slot=JSON.parse(el.textContent),slotWorks=Array.isArray(slot)?slot:slot.works;if(Array.isArray(slotWorks))out=out.concat(slotWorks)}catch(e){}}return uniqueWorks(out)}
function loadUserWorks(){var local=[];try{local=JSON.parse(localStorage.getItem(USER_WORK_KEY)||'[]')}catch(e){local=[]}USER_WORKS=uniqueWorks(readEmbeddedWorks().concat(local));var ids={};DATA.works.forEach(function(w){ids[w.id]=1});USER_WORKS.forEach(function(w){if(w&&w.id&&!ids[w.id]){DATA.works.push(w);ids[w.id]=1}})}
function saveUserWorks(){localStorage.setItem(USER_WORK_KEY,JSON.stringify(USER_WORKS))}
function workById(id){return DATA.works.find(function(w){return w.id===id})}
function loadCurated(){try{CURATED_IDS=JSON.parse(localStorage.getItem(CURATE_KEY)||'[]')}catch(e){CURATED_IDS=[]}CURATED_IDS=CURATED_IDS.filter(function(id,i,a){return a.indexOf(id)===i&&workById(id)})}
function saveCurated(){localStorage.setItem(CURATE_KEY,JSON.stringify(CURATED_IDS))}
function curatedWorks(){return CURATED_IDS.map(workById).filter(Boolean)}
function isCurated(id){return CURATED_IDS.indexOf(id)>=0}
function toggleCurate(id){var i=CURATED_IDS.indexOf(id);if(i>=0)CURATED_IDS.splice(i,1);else CURATED_IDS.push(id);saveCurated();renderCurateTray();renderGallery()}
function renderCurateTray(){var tray=document.getElementById('curateTray'),count=document.getElementById('curateCount'),strip=document.getElementById('curateStrip');if(!tray||!count||!strip)return;var works=curatedWorks();count.textContent=works.length;tray.classList.toggle('has-items',works.length>0);if(!works.length){strip.innerHTML='<div class="curate-empty">在作品卡片上点击“加入”，把面试时想重点讲的项目收进这里。</div>';return}strip.innerHTML=works.slice(-5).map(function(w){return'<div class="curate-thumb" data-open-work="'+esc(w.id)+'" data-cursor="打开"><img src="'+cardThumb(w)+'" alt="'+esc(w.title)+'"><button type="button" data-remove-curate="'+esc(w.id)+'">&times;</button></div>'}).join('');strip.querySelectorAll('[data-remove-curate]').forEach(function(btn){btn.addEventListener('click',function(e){e.stopPropagation();toggleCurate(btn.getAttribute('data-remove-curate'))})});strip.querySelectorAll('[data-open-work]').forEach(function(el){el.addEventListener('click',function(){openWorkById(el.getAttribute('data-open-work'))})})}
function getFW(){var w=DATA.works.slice();if(activeCat!=='all')w=w.filter(function(x){return x.categoryId===activeCat});else if(activeRoleCats.length)w=w.filter(function(x){return activeRoleCats.indexOf(x.categoryId)>=0});if(searchQ){var q=searchQ.toLowerCase();w=w.filter(function(x){return x.title.toLowerCase().indexOf(q)>=0||(x.description||'').toLowerCase().indexOf(q)>=0})}return w.sort(function(a,b){return b.createdAt-a.createdAt})}
function fmtD(ts){var d=new Date(ts);return d.getFullYear()+'.'+String(d.getMonth()+1).padStart(2,'0')+'.'+String(d.getDate()).padStart(2,'0')}
function sortedWorks(){return DATA.works.slice().sort(function(a,b){return b.createdAt-a.createdAt})}
function thumbOf(w){return cardThumb(w)}
function spotlightWorks(limit){var s=sortedWorks(),r=[],seen={};s.forEach(function(w){if(r.length<limit&&!seen[w.categoryId]){seen[w.categoryId]=true;r.push(w)}});s.forEach(function(w){if(r.length<limit&&r.indexOf(w)<0)r.push(w)});return r.slice(0,limit)}
function coverBackdropWork(){var order=['cat-19','cat-17','cat-16','cat-12','cat-5'];for(var i=0;i<order.length;i++){var hit=sortedWorks().find(function(w){return w.categoryId===order[i]&&thumbOf(w)});if(hit)return hit}return sortedWorks().find(function(w){return thumbOf(w)})}
function heroScanTags(w){var cat=catById(w.categoryId),base=cat?cat.name:'Portfolio';var map={'cat-1':'AIGC / 分镜 / 生成','cat-6':'UI / 路径 / 层级','cat-12':'产品 / 包装 / 场景','cat-16':'版式 / 识别 / 传播','cat-17':'空间 / 光影 / 氛围','cat-18':'角色 / IP / 表情','cat-19':'场景 / 镜头 / 色彩','cat-5':'插画 / 构图 / 情绪'};return map[w.categoryId]||base}
function renderHeroPreview(){var box=document.getElementById('heroPreview');if(!box)return;var picks=spotlightWorks(3);box.innerHTML=picks.map(function(w,i){var cat=catById(w.categoryId),label=cat?cat.icon+' '+cat.name:'Portfolio';return'<button class="hero-preview-shot" type="button" data-open-work="'+esc(w.id)+'" data-cursor="打开" data-scan-tags="'+esc(heroScanTags(w))+'"><img src="'+thumbOf(w)+'" alt="'+esc(w.title)+'" loading="eager"><span>'+esc(w.title)+'</span><small>'+esc(label)+'</small></button>'}).join('');box.querySelectorAll('[data-open-work]').forEach(function(btn){btn.addEventListener('click',function(){openWorkById(btn.getAttribute('data-open-work'))})})}
function renderMetrics(){var w=document.getElementById('metricWorks'),c=document.getElementById('metricCats'),f=document.getElementById('metricFocus');if(w)w.textContent=DATA.works.length;if(c)c.textContent=DATA.categories.length;if(f)f.textContent='AI+'}
var ROLE_PRESETS={aigc:{label:'AIGC 设计',cats:['cat-1','cat-18','cat-19','cat-5'],note:'突出 AI 生成、角色、场景和分镜能力。'},ui:{label:'UI/UX 设计',cats:['cat-6','cat-16'],note:'突出界面层级、信息组织和数字视觉表达。'},brand:{label:'品牌视觉',cats:['cat-16','cat-5','cat-12'],note:'突出平面传播、图形识别和品牌延展。'},product:{label:'文创产品',cats:['cat-12','cat-17','cat-19'],note:'突出文化转译、产品包装和空间场景。'}};
function applyRole(role){var cfg=ROLE_PRESETS[role];if(!cfg)return;activeRole=role;activeRoleCats=cfg.cats.slice();activeCat='all';searchQ='';var inp=document.getElementById('searchInput');if(inp)inp.value='';updateRoleUI();renderCatNav();renderGallery();document.getElementById('portfolioSection').scrollIntoView({behavior:'smooth'})}
function clearRole(){activeRole=null;activeRoleCats=[];updateRoleUI()}
function updateRoleUI(){var fb=document.getElementById('roleFeedback');document.querySelectorAll('.role-option').forEach(function(b){b.classList.toggle('active',b.dataset.role===activeRole)});if(!fb)return;if(activeRole){var cfg=ROLE_PRESETS[activeRole],cnt=DATA.works.filter(function(w){return cfg.cats.indexOf(w.categoryId)>=0}).length;fb.innerHTML='<span>当前浏览：'+cfg.label+' · '+cfg.note+'</span><b>'+cnt+' 件相关作品</b>'}else{fb.innerHTML='<span>当前浏览：全部作品</span><b>'+DATA.works.length+' 件作品待探索</b>'}}
function workDesc(w){if(w.description&&w.description.trim())return w.description;var cat=catById(w.categoryId),name=cat?cat.name:'综合设计';var map={'cat-1':'以连续画面组织叙事节奏，体现 AIGC 分镜、镜头情绪和视觉统一能力。','cat-6':'围绕界面层级、信息组织和视觉节奏展开，适合展示数字产品的页面表达能力。','cat-12':'将文化概念或品牌调性转化为可展示的产品、包装与场景视觉方案。','cat-16':'通过字体、版式、色彩和主视觉建立传播识别，适合活动视觉与品牌延展。','cat-17':'从空间氛围、动线和材质感出发，呈现场景概念与环境叙事能力。','cat-18':'围绕角色比例、表情姿态和文化符号建立可延展的 IP 视觉资产。','cat-19':'通过 AI 生成与后期筛选控制光影、构图和故事氛围，形成场景资产。','cat-5':'用图形、色彩和构图完成主题化表达，可延展到品牌、内容和文创应用。'};return map[w.categoryId]||('围绕'+name+'建立视觉方向，并通过最终图像验证设计表达。')}
function caseStory(w,i){var cat=catById(w.categoryId),brief=caseBrief(w),target='让项目从单张效果图变成可讲述、可复盘的设计案例。';var method='先明确主题与应用场景，再控制风格、构图、信息层级和最终展示方式。';var focus='面试时重点讲清楚目标、你的判断和最终交付，而不是只展示图片。';if(w.categoryId==='cat-12'){target='把 IP、包装或产品概念转化成能被理解的商业视觉。';method='从角色/品牌调性出发，统一造型、材质、包装画面和展示场景。';focus='重点讲文化元素如何变成产品语言，以及你如何控制系列一致性。'}else if(w.categoryId==='cat-6'){target='证明你能处理界面信息架构，而不是只做单张视觉图。';method='梳理分类、导航、卡片层级和检索路径，让作品浏览更高效。';focus='重点讲页面结构、用户路径、筛选逻辑和视觉层级。'}else if(w.categoryId==='cat-19'){target='用 AIGC 建立有故事感的场景视觉资产。';method='通过关键词、参考方向、生成筛选和后期统一控制光影与空间氛围。';focus='重点讲生成过程中的筛选标准、风格控制和最终可用场景。'}else if(w.categoryId==='cat-16'){target='把地域文化或活动主题转化成明确的传播视觉。';method='提炼符号、色彩和版式秩序，建立可用于海报和延展物料的主视觉。';focus='重点讲文化符号如何被转译，以及版式如何服务传播。'}return{no:String(i+1).padStart(2,'0'),title:w.title,cat:cat?cat.name:'综合设计',target:target,method:method,focus:focus,result:brief[2]}}
function renderCaseStories(){var box=document.getElementById('caseStudyGrid');if(!box)return;box.innerHTML=spotlightWorks(4).map(function(w,i){var s=caseStory(w,i);return'<article class="case-study"><small>Case '+s.no+' · '+esc(s.cat)+'</small><h4>'+esc(s.title)+'</h4><dl><div><dt>目标</dt><dd>'+esc(s.target)+'</dd></div><div><dt>方法</dt><dd>'+esc(s.method)+'</dd></div><div><dt>讲述重点</dt><dd>'+esc(s.focus)+'</dd></div></dl></article>'}).join('')}
function caseBrief(w){var m={'cat-6':['体验界面','梳理信息层级、视觉节奏和用户触点，强化页面的专业感与可读性。','产出：界面视觉 / 页面结构 / 交互表达'],'cat-16':['平面传播','用版式、字体和图像秩序传递主题情绪，适合海报与活动视觉展示。','产出：海报排版 / 视觉主图 / 应用延展'],'cat-12':['产品转化','把文化或品牌概念转化为可被理解、可被展示的产品视觉方案。','产出：产品造型 / 包装视觉 / 场景图'],'cat-17':['空间叙事','从环境氛围、动线和材料感出发，建立更完整的空间表达。','产出：空间概念 / 场景渲染 / 氛围板'],'cat-18':['角色资产','围绕角色性格、比例、服饰和故事语境建立可延展的视觉资产。','产出：角色设定 / 表情姿态 / 系列化形象'],'cat-19':['场景资产','用 AI 与后期控制光影、景深和构图，完成具有故事感的场景视觉。','产出：场景主图 / 视觉世界观 / 分镜素材'],'cat-1':['AIGC 分镜','通过连续画面组织情绪递进，展示 AI 生成与叙事设计的结合。','产出：分镜图组 / 情绪节奏 / 视频素材'],'cat-5':['插画表达','以图形、色彩和构图完成主题化表达，适合品牌和内容视觉延展。','产出：插画主视觉 / 系列图形 / 衍生应用']};return m[w.categoryId]||['综合设计','围绕项目目标建立视觉方向，并通过最终图像验证设计表达。','产出：视觉方案 / 展示页面 / 项目说明']}
function renderCaseRail(){var rail=document.getElementById('caseRail');if(!rail)return;var cases=spotlightWorks(4);rail.innerHTML=cases.map(function(w,i){var cat=catById(w.categoryId),brief=caseBrief(w),no=String(i+1).padStart(2,'0');return'<article class="case-card"><div class="case-thumb"><img src="'+thumbOf(w)+'" alt="'+esc(w.title)+'" loading="lazy"></div><div class="case-body"><div class="case-meta"><span>Case '+no+'</span><span>'+esc(cat?cat.name:'未分类')+'</span></div><h3 class="case-title">'+esc(w.title)+'</h3><p class="case-brief"><b>'+brief[0]+'</b> · '+brief[1]+'</p><p class="case-result">'+brief[2]+'</p><button class="case-open" data-open-work="'+esc(w.id)+'">打开作品</button></div></article>'}).join('');rail.querySelectorAll('[data-open-work]').forEach(function(btn){btn.addEventListener('click',function(){openWorkById(btn.getAttribute('data-open-work'))})});wireTilt();refreshMotionTargets();wireMagneticControls()}
function openWorkById(id){activeCat='all';searchQ='';clearRole();var inp=document.getElementById('searchInput');if(inp)inp.value='';renderCatNav();renderGallery();var idx=fw.findIndex(function(w){return w.id===id});if(idx>=0)openLB(idx)}
function categoryMeta(id){var map={
'cat-1':{label:'AIGC 视觉生成',statement:'展示你能用 AI 做连续画面、风格控制和叙事筛选，而不是只生成单张好看的图。',proof:['提示词与风格控制','连续画面一致性','后期筛选与统一'],keys:['AIGC','分镜','风格控制','叙事节奏']},
'cat-12':{label:'文创与产品转译',statement:'展示你能把文化符号、IP 形象或品牌调性转成可展示、可延展的产品视觉。',proof:['概念转产品语言','包装与展示场景','系列化视觉延展'],keys:['产品造型','包装视觉','文创落地','系列系统']},
'cat-16':{label:'品牌与平面传播',statement:'展示你能用字体、版式、主视觉和色彩建立传播识别，让画面服务主题而不是只做装饰。',proof:['主视觉建立','版式秩序','活动与品牌延展'],keys:['海报','VI','版式','传播识别']},
'cat-17':{label:'空间与环境表达',statement:'展示你能处理空间氛围、动线、材质和场景叙事，适合环境设计与展示表达。',proof:['空间概念表达','材质与光影氛围','场景叙事组织'],keys:['空间','氛围','动线','材质']},
'cat-18':{label:'角色与 IP 资产',statement:'展示你能围绕角色比例、服饰、表情和文化符号建立可延展的视觉资产。',proof:['角色设定','表情姿态系统','IP 延展可能性'],keys:['角色','IP','设定','文化符号']},
'cat-19':{label:'场景视觉资产',statement:'展示你能控制光影、构图和故事氛围，把场景图变成可用于叙事和展示的视觉资产。',proof:['世界观氛围','光影与构图控制','可用场景素材'],keys:['场景','光影','世界观','概念图']},
'cat-5':{label:'插画与图形表达',statement:'展示你能通过图形、色彩和构图完成主题化表达，并延展到内容、品牌和文创应用。',proof:['主题图形提炼','色彩情绪控制','应用延展能力'],keys:['插画','图形','色彩','主题表达']},
'cat-6':{label:'UI/UX 界面组织',statement:'展示你能处理信息架构、页面层级和交互路径，让视觉服务真实浏览效率。',proof:['信息层级整理','页面节奏控制','筛选与交互路径'],keys:['UI','信息架构','交互','界面视觉']}
};return map[id]||{label:'综合设计表达',statement:'展示你围绕项目目标建立视觉方向，并用最终图像证明设计表达。',proof:['主题判断','视觉执行','交付表达'],keys:['综合','视觉','表达']}}
function categoryWorks(id){return DATA.works.filter(function(w){return w.categoryId===id}).sort(function(a,b){return b.createdAt-a.createdAt})}
function categoryIdentity(id){var map={
'cat-1':{tone:'分镜实验室',mood:'连续画面 / 生成节奏',ref:'STORYBOARD LAB'},
'cat-12':{tone:'包装陈列感',mood:'货架 / 材质 / 商业展示',ref:'PACKAGING DISPLAY'},
'cat-16':{tone:'主视觉海报墙',mood:'版式秩序 / 传播物料',ref:'POSTER SYSTEM'},
'cat-17':{tone:'空间材料板',mood:'平面 / 动线 / 光影',ref:'SPATIAL BOARD'},
'cat-18':{tone:'角色设定集',mood:'三视图 / 表情 / 姿态',ref:'CHARACTER SHEET'},
'cat-19':{tone:'电影取景框',mood:'景深 / 光影 / 场景叙事',ref:'CINEMATIC FRAME'},
'cat-5':{tone:'插画草图本',mood:'手绘 / 色彩 / 图形延展',ref:'ILLUSTRATION BOOK'},
'cat-6':{tone:'界面网格感',mood:'组件 / 路径 / 信息层级',ref:'INTERFACE GRID'}
};return map[id]||{tone:'视觉档案',mood:'主题 / 过程 / 交付',ref:'VISUAL FILE'}}
function showCategoryArchive(id){setPortfolioView('archive',false);clearRole();activeCat=id;searchQ='';var inp=document.getElementById('searchInput');if(inp)inp.value='';renderCatNav();renderGallery();var nav=document.getElementById('categoryNav');if(nav)nav.scrollIntoView({behavior:'smooth',block:'start'})}
function renderCategoryStories(){var box=document.getElementById('categoryStories');if(!box)return;var html=DATA.categories.map(function(cat,i){var works=categoryWorks(cat.id);if(!works.length)return'';var meta=categoryMeta(cat.id),identity=categoryIdentity(cat.id),feature=works[0],support=works.slice(1,3),no=String(i+1).padStart(2,'0');var shots='<button class="category-main-shot" type="button" data-open-work="'+esc(feature.id)+'" data-cursor="代表作"><img src="'+cardThumb(feature)+'" alt="'+esc(feature.title)+'" loading="lazy"><span class="category-shot-label">代表作</span></button>'+support.map(function(w,j){return'<button class="category-thumb-shot" type="button" data-open-work="'+esc(w.id)+'" data-cursor="补充图"><img src="'+cardThumb(w)+'" alt="'+esc(w.title)+'" loading="lazy"><span class="category-shot-label">证据 '+(j+1)+'</span></button>'}).join('');return'<article class="category-story" data-cat="'+esc(cat.id)+'" data-identity="'+esc(identity.tone)+'"><div class="category-visual">'+shots+'<div class="category-signature" aria-hidden="true"><b>'+esc(identity.ref)+'</b><span>'+esc(identity.tone)+'</span></div></div><div class="category-body"><div><div class="category-index"><span>'+no+' / '+esc(cat.icon)+' '+esc(meta.label)+'</span><span class="category-count">'+works.length+' WORKS</span></div><div class="category-identity"><b>'+esc(identity.tone)+'</b><span>'+esc(identity.mood)+'</span></div><h3 class="category-title">'+esc(cat.name)+'</h3><p class="category-statement">'+esc(meta.statement)+'</p><div class="category-proof">'+meta.proof.map(function(p){return'<span>'+esc(p)+'</span>'}).join('')+'</div></div><div><div class="category-keywords">'+meta.keys.map(function(k){return'<span>'+esc(k)+'</span>'}).join('')+'</div><div class="category-actions"><button class="category-open" type="button" data-open-work="'+esc(feature.id)+'" data-cursor="打开">打开代表作</button><button class="category-filter" type="button" data-filter-cat="'+esc(cat.id)+'" data-cursor="筛选">查看这一类</button></div></div></div></article>'}).join('');box.innerHTML=html||'<div class="category-empty">还没有可用于分类策展的作品。</div>';box.querySelectorAll('[data-open-work]').forEach(function(btn){btn.addEventListener('click',function(){openWorkById(btn.getAttribute('data-open-work'))})});box.querySelectorAll('[data-filter-cat]').forEach(function(btn){btn.addEventListener('click',function(){showCategoryArchive(btn.getAttribute('data-filter-cat'))})});refreshMotionTargets();wireMagneticControls()}
function renderCatNav(){var n=document.getElementById('categoryNav');var h='<button class="cat-filter-btn'+(activeCat==='all'&&!activeRole?' active':'')+'" data-cat="all">全部 <span class="cat-count">'+DATA.works.length+'</span></button>';
if(activeRole){h+='<button class="cat-filter-btn active" data-role-reset="1">岗位匹配：'+esc(ROLE_PRESETS[activeRole].label)+' <span class="cat-count">'+getFW().length+'</span></button>'}
DATA.categories.forEach(function(c){var cnt=DATA.works.filter(function(w){return w.categoryId===c.id}).length;h+='<button class="cat-filter-btn'+(activeCat===c.id?' active':'')+'" data-cat="'+c.id+'">'+c.icon+' '+esc(c.name)+' <span class="cat-count">'+cnt+'</span></button>'});
n.innerHTML=h;n.querySelectorAll('[data-role-reset]').forEach(function(b){b.addEventListener('click',function(){clearRole();activeCat='all';renderCatNav();renderGallery()})});n.querySelectorAll('[data-cat]').forEach(function(b){b.addEventListener('click',function(){clearRole();activeCat=b.dataset.cat;renderCatNav();renderGallery()})});wireMagneticControls()}

function renderGallery(){
  var g=document.getElementById('gallery');fw=getFW();
  if(!fw.length){g.innerHTML='<p style="text-align:center;padding:4rem;color:var(--text-muted)">暂无作品</p>';return}
  g.innerHTML=fw.map(function(w,i){
    var cat=catById(w.categoryId),ci=cat?cat.icon:'&#10067;',cn=cat?esc(cat.name):'未分类',dl=Math.min(i*.04,.6);
    var thumbSrc='';
    thumbSrc=cardThumb(w)
    var m='<div class="card-media"><img src="'+thumbSrc+'" alt="'+esc(w.title)+'" loading="lazy">'+(w.mediaType==='video'?'<div class="play-badge"></div>':'')+'</div>';
    return'<div class="work-card" data-idx="'+i+'" data-cursor="打开" style="animation-delay:'+dl+'s"><button class="card-pin'+(isCurated(w.id)?' active':'')+'" type="button" data-cursor="'+(isCurated(w.id)?'移除':'加入')+'" data-pin-work="'+esc(w.id)+'">'+(isCurated(w.id)?'已加入':'加入')+'</button><span class="card-no">'+String(i+1).padStart(2,'0')+'</span>'+m+'<div class="card-info"><span class="card-badge">'+ci+' '+cn+'</span><h3 class="card-title">'+esc(w.title)+'</h3><p class="card-desc">'+esc(workDesc(w))+'</p><p class="card-date">'+fmtD(w.createdAt)+'</p></div></div>'}).join('');
  g.querySelectorAll('.work-card').forEach(function(c){c.addEventListener('click',function(){openLB(+c.dataset.idx)})});g.querySelectorAll('[data-pin-work]').forEach(function(b){b.addEventListener('click',function(e){e.stopPropagation();toggleCurate(b.getAttribute('data-pin-work'))})});wireTilt();refreshMotionTargets();wireMagneticControls()}

function projectTools(w){var map={'cat-1':'AIGC / 分镜组织 / 风格筛选','cat-6':'UI 结构 / 信息层级 / 页面节奏','cat-12':'产品概念 / 包装视觉 / 场景展示','cat-16':'版式系统 / 主视觉 / 应用延展','cat-17':'空间氛围 / 材质光影 / 场景叙事','cat-18':'角色设定 / IP 延展 / 姿态表情','cat-19':'场景生成 / 光影控制 / 后期统一','cat-5':'插画构图 / 色彩情绪 / 图形延展'};return map[w.categoryId]||'视觉方案 / 图像执行 / 展示交付'}
function projectFlowSteps(w){if(w.categoryId==='cat-1'||w.categoryId==='cat-19')return['概念方向','提示生成','筛选统一','视觉交付'];if(w.categoryId==='cat-6')return['信息架构','界面层级','交互路径','页面交付'];if(w.categoryId==='cat-12')return['文化提炼','产品转译','包装展示','场景落地'];return['主题判断','视觉执行','细节统一','展示交付']}
function promptTokens(w){var map={'cat-1':['角色情绪','镜头节奏','毛发质感','奇幻氛围','分镜连贯'],'cat-6':['信息层级','暗色界面','筛选路径','组件节奏','可读性'],'cat-12':['文化转译','包装材质','产品场景','收藏属性','商业展示'],'cat-16':['版式秩序','主视觉','传播延展','字形对比','品牌语气'],'cat-17':['空间动线','材质光影','场景氛围','尺度关系','室内叙事'],'cat-18':['IP 设定','表情姿态','角色比例','道具细节','三视图'],'cat-19':['自然光影','色彩层次','空间纵深','镜头构图','环境叙事'],'cat-5':['手绘质感','色彩情绪','图形延展','构图重心','插画应用']};return map[w.categoryId]||['概念关键词','视觉风格','细节控制','展示场景','交付表达']}
function projectStoryboard(w,story,brief){var cat=catById(w.categoryId),catName=cat?cat.name:'综合设计',flow=projectFlowSteps(w),tokens=promptTokens(w),desc=workDesc(w);return[
  {key:'brief',label:'Brief',title:'项目目标',body:story.target,points:['项目类型：'+catName,'切入角度：'+brief[0],'最终产出：'+story.result]},
  {key:'process',label:'Process',title:'设计过程',body:story.method,points:flow.map(function(s,i){return String(i+1).padStart(2,'0')+' · '+s})},
  {key:'detail',label:'Detail',title:'细节判断',body:story.focus,points:tokens.slice(0,4).map(function(t){return '控制点：'+t})},
  {key:'final',label:'Final',title:'最终交付',body:desc,points:[brief[2],'能力证明：'+projectTools(w),'面试讲述：目标、过程、结果三段式展开']}
]}
function renderStoryPanel(steps,active){var panel=document.getElementById('lbStoryPanel');if(!panel||!steps||!steps.length)return;var s=steps[active]||steps[0];panel.innerHTML='<div class="story-panel-head"><span>'+esc(s.label)+'</span><b>'+esc(s.title)+'</b></div><p>'+esc(s.body)+'</p><ul>'+s.points.map(function(p){return'<li>'+esc(p)+'</li>'}).join('')+'</ul>'}
function bindStoryTabs(steps){var tabs=document.getElementById('lbStoryTabs');if(!tabs)return;tabs.innerHTML=steps.map(function(s,i){return'<button type="button" class="'+(i===0?'active':'')+'" data-story-step="'+i+'" style="--tab:'+i+'">'+esc(s.label)+'</button>'}).join('');renderStoryPanel(steps,0);tabs.querySelectorAll('[data-story-step]').forEach(function(btn){btn.addEventListener('click',function(){var n=+btn.getAttribute('data-story-step');tabs.querySelectorAll('[data-story-step]').forEach(function(b){b.classList.toggle('active',b===btn)});renderStoryPanel(steps,n)})})}

// ★ 核心修改：视频使用 mediaBase64 创建 <video> 标签播放 ★
function openLB(idx){
  if(idx<0||idx>=fw.length)return;lbIdx=idx;var w=fw[idx],m=document.getElementById('lbMedia');
  if(w.mediaType==='video'){
    if(w.mediaBase64){
      m.innerHTML='<video src="'+w.mediaBase64+'" controls autoplay playsinline preload="auto"></video>';
    }else if(w.thumbnail){
      m.innerHTML='<img src="'+w.thumbnail+'" alt="'+esc(w.title)+'"><p class="media-note">视频数据未包含在此文件中</p>';
    }else{
      m.innerHTML='<p class="media-note">视频不可用</p>';
    }
  }else{
    m.innerHTML='<img src="'+cardThumb(w)+'" alt="'+esc(w.title)+'">';
  }
  var story=caseStory(w,idx),brief=caseBrief(w);
  document.getElementById('lbStep').textContent=String(idx+1).padStart(2,'0')+' / '+String(fw.length).padStart(2,'0');
  document.getElementById('lbTitle').textContent=w.title;document.getElementById('lbDesc').textContent=workDesc(w);
  var proof=document.getElementById('lbProof');if(proof)proof.innerHTML=[
    ['项目目标',story.target],
    ['设计方法',story.method],
    ['讲述重点',story.focus],
    ['工具与能力',projectTools(w)]
  ].map(function(p){return'<div class="project-proof"><b>'+esc(p[0])+'</b><span>'+esc(p[1])+'</span></div>'}).join('');
  var prompt=document.getElementById('lbPrompt');if(prompt)prompt.innerHTML=promptTokens(w).map(function(t,i){return'<i style="--chip:'+i+'">'+esc(t)+'</i>'}).join('');
  bindStoryTabs(projectStoryboard(w,story,brief));
  var flow=document.getElementById('lbFlow');if(flow)flow.innerHTML=projectFlowSteps(w).map(function(s,i){return'<i style="--step:'+i+'">'+esc(s)+'</i>'}).join('');
  var cat=catById(w.categoryId),ce=document.getElementById('lbCat');
  if(cat){ce.textContent=cat.icon+' '+cat.name;ce.style.display='inline-block'}else{ce.style.display='none'}
  document.getElementById('lightbox').style.display='flex';document.getElementById('lightbox').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';
}

// ★ 修改：关闭时暂停视频 ★
function closeLB(){var v=document.querySelector('#lbMedia video');if(v)v.pause();var lb=document.getElementById('lightbox');lb.style.display='none';lb.setAttribute('aria-hidden','true');document.getElementById('lbMedia').innerHTML='';document.body.style.overflow='';lbIdx=-1}
function navLB(d){var n=lbIdx+d;if(n<0)n=fw.length-1;if(n>=fw.length)n=0;openLB(n)}
function openRandomWork(){var pool=getFW();if(!pool.length)pool=sortedWorks();fw=pool;openLB(Math.floor(Math.random()*pool.length))}
function updateScrollMeter(){var doc=document.documentElement,max=Math.max(1,doc.scrollHeight-window.innerHeight),pct=Math.round((window.scrollY/max)*100),txt=document.getElementById('scrollPct'),fill=document.getElementById('scrollFill'),cockpit=document.querySelector('.interaction-cockpit'),contact=document.getElementById('contactSection'),portfolio=document.getElementById('portfolioSection');var inFocus=false;if(contact){var r=contact.getBoundingClientRect();inFocus=r.top<window.innerHeight*.86&&r.bottom>window.innerHeight*.18}if(portfolio&&window.innerWidth<760){var pr=portfolio.getBoundingClientRect();if(pr.top<window.innerHeight*.92&&pr.bottom>window.innerHeight*.12)inFocus=true}var nearEnd=window.scrollY>max-window.innerHeight*.72;if(nearEnd)inFocus=true;if(txt)txt.textContent=Math.min(99,pct);if(fill)fill.style.setProperty('--p',Math.min(100,pct)+'%');if(cockpit){cockpit.classList.toggle('visible',window.scrollY>window.innerHeight*.35&&!inFocus);document.body.classList.toggle('in-contact',inFocus)}}
var tourSteps=[{target:'cover',title:'第一眼说明你的方向',text:'首屏把个人定位、求职方向和代表作品合在一起，让招聘方先看到你能做什么。'},{target:'profileSection',title:'能力结构先于作品数量',text:'这里把经历拆成策略、生成、视觉和落地四块，避免作品集只像图片集合。'},{target:'roleLab',title:'按岗位重新组织作品',text:'选择目标岗位后，作品库会筛出更匹配的内容，面试时可以快速切换展示重点。'},{target:'caseSection',title:'精选案例承担叙事',text:'案例卡片用目标、方法和产出描述项目，不只展示缩略图。'},{target:'portfolioSection',title:'作品库负责完整检索',text:'最后保留搜索、分类和灯箱，方便按类别快速检查全部作品。'}],tourIndex=0;
function showTourStep(){var s=tourSteps[tourIndex],target=document.getElementById(s.target);if(target)target.scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('tourStep').textContent=String(tourIndex+1).padStart(2,'0')+' / '+String(tourSteps.length).padStart(2,'0');document.getElementById('tourTitle').textContent=s.title;document.getElementById('tourText').textContent=s.text}
function startTour(){closeLB();var o=document.getElementById('tourOverlay');tourIndex=0;o.classList.add('active');o.setAttribute('aria-hidden','false');showTourStep()}
function closeTour(){var o=document.getElementById('tourOverlay');o.classList.remove('active');o.setAttribute('aria-hidden','true')}
function nextTour(d){tourIndex+=d;if(tourIndex<0)tourIndex=tourSteps.length-1;if(tourIndex>=tourSteps.length)tourIndex=0;showTourStep()}
function deckPointCopy(w){var brief=caseBrief(w),cat=catById(w.categoryId);return[{b:'项目切入',s:brief[0]+' · '+(cat?cat.name:'综合设计')},{b:'讲述重点',s:brief[1]},{b:'交付结果',s:brief[2]}]}
function renderDeck(){if(!deckWorks.length)return;var w=deckWorks[deckIndex],cat=catById(w.categoryId),media=document.getElementById('deckMedia');if(w.mediaType==='video'&&w.mediaBase64){media.innerHTML='<video src="'+w.mediaBase64+'" controls autoplay muted playsinline preload="auto"></video>'}else{media.innerHTML='<img src="'+cardThumb(w)+'" alt="'+esc(w.title)+'">'}document.getElementById('deckStep').textContent=String(deckIndex+1).padStart(2,'0')+' / '+String(deckWorks.length).padStart(2,'0');document.getElementById('deckCat').textContent=cat?cat.name:'Portfolio';document.getElementById('deckTitle').textContent=w.title;document.getElementById('deckDesc').textContent=w.description||'这件作品适合在面试中结合项目目标、设计判断和最终视觉效果进行讲述。';document.getElementById('deckPoints').innerHTML=deckPointCopy(w).map(function(p){return'<div class="deck-point"><b>'+esc(p.b)+'</b><span>'+esc(p.s)+'</span></div>'}).join('');document.getElementById('deckThumbs').innerHTML=deckWorks.map(function(x,i){return'<button class="deck-thumb'+(i===deckIndex?' active':'')+'" type="button" data-deck-go="'+i+'"><img src="'+cardThumb(x)+'" alt="'+esc(x.title)+'"></button>'}).join('');document.querySelectorAll('[data-deck-go]').forEach(function(btn){btn.addEventListener('click',function(){deckIndex=+btn.getAttribute('data-deck-go');renderDeck()})})}
function openDeck(){closeLB();closeTour();closeEditor();deckWorks=curatedWorks();if(!deckWorks.length)deckWorks=spotlightWorks(6);deckIndex=0;renderDeck();var o=document.getElementById('deckOverlay');o.classList.add('active');o.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeDeck(){var v=document.querySelector('#deckMedia video');if(v)v.pause();var o=document.getElementById('deckOverlay');o.classList.remove('active');o.setAttribute('aria-hidden','true');document.getElementById('deckMedia').innerHTML='';document.body.style.overflow=''}
function navDeck(d){if(!deckWorks.length)return;deckIndex+=d;if(deckIndex<0)deckIndex=deckWorks.length-1;if(deckIndex>=deckWorks.length)deckIndex=0;renderDeck()}
function initSmartCursor(){var c=document.getElementById('smartCursor');if(!c||!window.matchMedia('(pointer:fine)').matches){if(c)c.style.display='none';return}document.addEventListener('pointermove',function(e){c.style.setProperty('--x',e.clientX+'px');c.style.setProperty('--y',e.clientY+'px');var t=e.target.closest('[data-cursor],button,a,.work-card,.case-card');if(!t){c.classList.remove('active');return}var label=t.getAttribute('data-cursor')||(t.classList.contains('work-card')?'打开':'查看');c.textContent=label.slice(0,4);c.classList.add('active')});document.addEventListener('pointerleave',function(){c.classList.remove('active')})}
function wireTilt(){if(!window.matchMedia('(pointer:fine)').matches)return;document.querySelectorAll('.work-card,.case-card,.hero-dashboard').forEach(function(el){if(el.dataset.tiltReady)return;el.dataset.tiltReady='1';el.addEventListener('pointermove',function(e){var r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,rx=((.5-y/r.height)*8).toFixed(2),ry=((x/r.width-.5)*10).toFixed(2);el.style.setProperty('--mx',x+'px');el.style.setProperty('--my',y+'px');el.style.setProperty('--rx',rx+'deg');el.style.setProperty('--ry',ry+'deg');el.classList.add('tilt')});el.addEventListener('pointerleave',function(){el.classList.remove('tilt');el.style.removeProperty('--rx');el.style.removeProperty('--ry')})})}
var MOTION_OBSERVER=null,MOTION_REDUCED=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function splitHeroTitle(){var title=document.querySelector('.cover-title');if(!title||title.dataset.motionSplit)return;title.dataset.motionSplit='1';title.classList.add('motion-split');var delay=0;title.querySelectorAll('span').forEach(function(line){var chars=Array.from(line.textContent);line.textContent='';chars.forEach(function(ch){var s=document.createElement('span');s.className='motion-letter';s.style.setProperty('--letter-delay',delay+'ms');s.textContent=ch===' '?' ':ch;line.appendChild(s);delay+=56})})}
function setupMotionObserver(){if(MOTION_REDUCED){document.body.classList.add('reduce-motion');return null}if(MOTION_OBSERVER)return MOTION_OBSERVER;MOTION_OBSERVER=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');MOTION_OBSERVER.unobserve(entry.target)}})},{threshold:.16,rootMargin:'0px 0px -8% 0px'});return MOTION_OBSERVER}
function markMotion(nodes,variant,baseDelay){var obs=setupMotionObserver();if(!obs)return;Array.prototype.forEach.call(nodes,function(el,i){if(el.dataset.motionReady)return;el.dataset.motionReady='1';el.classList.add('motion-reveal');if(variant)el.classList.add(variant);el.style.setProperty('--motion-delay',Math.min((baseDelay||0)+i*70,520)+'ms');obs.observe(el)})}
function refreshMotionTargets(){if(MOTION_REDUCED)return;markMotion(document.querySelectorAll('.section-header'),'motion-clip',0);markMotion(document.querySelectorAll('.profile-statement,.role-lab,.archive-advice,.contact-left'),'motion-slide-left',0);markMotion(document.querySelectorAll('.capability-item,.process-step,.snapshot-item,.role-option,.contact-card,.category-proof span'),'motion-scale',0);markMotion(document.querySelectorAll('.case-card,.category-story'),'motion-scale',0);markMotion(document.querySelectorAll('.case-study'),'motion-slide-right',0);markMotion(document.querySelectorAll('.work-card'),'motion-scale',0)}
function wireMagneticControls(){if(!window.matchMedia('(pointer:fine)').matches||MOTION_REDUCED)return;document.querySelectorAll('.btn,.case-open,.cat-filter-btn,.role-option,.contact-email,.cockpit-btn,.scene-dot,.category-open,.category-filter').forEach(function(el){if(el.dataset.magneticReady)return;el.dataset.magneticReady='1';el.classList.add('motion-magnetic');el.addEventListener('pointermove',function(e){var r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/r.width,y=(e.clientY-r.top-r.height/2)/r.height;el.style.setProperty('--mag-x',(x*14).toFixed(2)+'px');el.style.setProperty('--mag-y',(y*10).toFixed(2)+'px')});el.addEventListener('pointerleave',function(){el.style.removeProperty('--mag-x');el.style.removeProperty('--mag-y')})})}
function wireHeroParallax(){var cover=document.getElementById('cover');if(!cover||MOTION_REDUCED)return;var ticking=false,px=0,py=0;function apply(){document.body.style.setProperty('--parallax-x',px+'px');document.body.style.setProperty('--parallax-y',py+'px');ticking=false}cover.addEventListener('pointermove',function(e){var r=cover.getBoundingClientRect();px=((e.clientX-r.left)/r.width-.5)*14;py=((e.clientY-r.top)/r.height-.5)*14;if(!ticking){requestAnimationFrame(apply);ticking=true}});cover.addEventListener('pointerleave',function(){px=0;py=0;apply()})}
function wireHeroRevealer(){var cover=document.getElementById('cover');if(!cover)return;function move(clientX,clientY){var r=cover.getBoundingClientRect(),x=Math.max(0,Math.min(r.width,clientX-r.left)),y=Math.max(0,Math.min(r.height,clientY-r.top));cover.style.setProperty('--scan-x',x+'px');cover.style.setProperty('--scan-y',y+'px');cover.classList.add('is-scanning')}if(!cover.dataset.revealReady){cover.dataset.revealReady='1';cover.addEventListener('pointermove',function(e){move(e.clientX,e.clientY)});cover.addEventListener('pointerleave',function(){cover.classList.remove('is-scanning')});cover.addEventListener('touchmove',function(e){var t=e.touches&&e.touches[0];if(t)move(t.clientX,t.clientY)},{passive:true})}document.querySelectorAll('.hero-preview-shot').forEach(function(btn){if(btn.dataset.scanReady)return;btn.dataset.scanReady='1';btn.addEventListener('pointerenter',function(){cover.classList.add('is-scanning','is-previewing');cover.setAttribute('data-scan-tags',btn.getAttribute('data-scan-tags')||'Creative proof')});btn.addEventListener('pointerleave',function(){cover.classList.remove('is-previewing')})})}
function setPortfolioView(view,doScroll){portfolioView=view==='archive'?'archive':'curation';var section=document.getElementById('portfolioSection');if(section)section.setAttribute('data-view',portfolioView);document.querySelectorAll('[data-portfolio-view]').forEach(function(btn){btn.classList.toggle('active',btn.getAttribute('data-portfolio-view')===portfolioView);btn.setAttribute('aria-selected',btn.classList.contains('active')?'true':'false')});if(doScroll!==false&&section)section.scrollIntoView({behavior:'smooth',block:'start'})}
function bindPortfolioSwitch(){setPortfolioView(portfolioView,false);document.querySelectorAll('[data-portfolio-view]').forEach(function(btn){if(btn.dataset.switchReady)return;btn.dataset.switchReady='1';btn.addEventListener('click',function(){setPortfolioView(btn.getAttribute('data-portfolio-view'))})})}
function bindContactActions(){var copy=document.getElementById('copyEmail');if(!copy||copy.dataset.copyReady)return;copy.dataset.copyReady='1';copy.addEventListener('click',function(){var email='3237205525@qq.com';function done(){copy.textContent='已复制';setTimeout(function(){copy.textContent='复制邮箱'},1600)}if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(email).then(done).catch(function(){location.href='mailto:'+email})}else{location.href='mailto:'+email}})}

function wireSceneRipples(){document.querySelectorAll('.scene-dot').forEach(function(dot){if(dot.dataset.rippleReady)return;dot.dataset.rippleReady='1';dot.addEventListener('click',function(){dot.classList.remove('scene-pop');void dot.offsetWidth;dot.classList.add('scene-pop')})})}
function initPortfolioMotion(){document.body.classList.add('motion-ready');splitHeroTitle();refreshMotionTargets();wireMagneticControls();wireHeroParallax();wireHeroRevealer();wireSceneRipples()}
function isOwnerMode(){return new URLSearchParams(location.search).get('owner')==='1'} function openEditor(){if(!isOwnerMode())return;var d=document.getElementById('editorDrawer');renderEditor();d.classList.add('open');d.setAttribute('aria-hidden','false')}
function closeEditor(){var d=document.getElementById('editorDrawer');d.classList.remove('open');d.setAttribute('aria-hidden','true')}
function renderEditor(){var sel=document.getElementById('editCategory');if(sel&&!sel.options.length){sel.innerHTML=DATA.categories.map(function(c){return'<option value="'+c.id+'">'+esc(c.icon+' '+c.name)+'</option>'}).join('')}var list=document.getElementById('editorList');if(!list)return;if(!USER_WORKS.length){list.innerHTML='<p style="color:var(--text-muted);font-size:.75rem">还没有通过编辑器新增作品。</p>';return}list.innerHTML=USER_WORKS.slice().reverse().map(function(w){var cat=catById(w.categoryId);return'<div class="editor-item"><img src="'+cardThumb(w)+'" alt=""><div><b>'+esc(w.title)+'</b><span>'+(cat?esc(cat.name):'未分类')+' · '+fmtD(w.createdAt)+'</span></div><button type="button" data-del-work="'+esc(w.id)+'">删除</button></div>'}).join('');list.querySelectorAll('[data-del-work]').forEach(function(btn){btn.addEventListener('click',function(){deleteUserWork(btn.getAttribute('data-del-work'))})})}
function refreshAll(){renderHeroPreview();renderMetrics();renderCaseRail();renderCaseStories();renderCategoryStories();renderCatNav();renderGallery();updateRoleUI();renderEditor();renderCurateTray()}
function addUserWork(){var title=document.getElementById('editTitle').value.trim(),desc=document.getElementById('editDesc').value.trim(),cat=document.getElementById('editCategory').value,file=document.getElementById('editFile').files[0];if(!title){alert('请先填写作品名称');return}if(!file){alert('请选择图片或视频文件');return}var reader=new FileReader();reader.onload=function(){var mediaType=file.type.indexOf('video/')===0?'video':'image',work={id:'user-'+Date.now(),title:title,description:desc,categoryId:cat,mediaType:mediaType,createdAt:Date.now(),mediaBase64:reader.result,thumbnail:mediaType==='image'?reader.result:''};USER_WORKS.push(work);DATA.works.push(work);saveUserWorks();document.getElementById('editTitle').value='';document.getElementById('editDesc').value='';document.getElementById('editFile').value='';activeCat='all';clearRole();refreshAll();document.getElementById('portfolioSection').scrollIntoView({behavior:'smooth'})};reader.readAsDataURL(file)}
function deleteUserWork(id){USER_WORKS=USER_WORKS.filter(function(w){return w.id!==id});DATA.works=DATA.works.filter(function(w){return w.id!==id});CURATED_IDS=CURATED_IDS.filter(function(x){return x!==id});saveUserWorks();saveCurated();refreshAll()}
function exportUserWorks(){var data=JSON.stringify({version:1,exportedAt:new Date().toISOString(),works:USER_WORKS},null,2),blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='xiaokai-portfolio-new-works.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function importUserWorks(file){var reader=new FileReader();reader.onload=function(){try{var parsed=JSON.parse(reader.result),works=Array.isArray(parsed)?parsed:parsed.works;if(!Array.isArray(works))throw new Error('JSON 中没有 works 数组');var ids={};USER_WORKS.forEach(function(w){ids[w.id]=1});DATA.works.forEach(function(w){ids[w.id]=1});works.forEach(function(w){if(w&&w.id&&!ids[w.id]){USER_WORKS.push(w);DATA.works.push(w);ids[w.id]=1}});saveUserWorks();refreshAll();alert('导入完成')}catch(e){alert('导入失败：'+e.message)}};reader.readAsText(file)}
function safeJson(data){return JSON.stringify(data,null,2).replace(/</g,'\\u003c')}
function downloadTextFile(name,text,type){var blob=new Blob([text],{type:type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function generateStandaloneHtml(){var works=uniqueWorks(USER_WORKS);if(!works.length){alert('还没有通过编辑器新增作品，先添加或导入作品后再生成新版 HTML。');return}var root=document.documentElement.cloneNode(true),slot=root.querySelector('#portfolioEmbeddedWorks');if(!slot){alert('缺少作品数据槽，无法生成新版 HTML。');return}['heroPreview','categoryNav','caseRail','gallery','editorList','lbMedia','curateStrip','deckMedia','deckPoints','deckThumbs'].forEach(function(id){var el=root.querySelector('#'+id);if(el)el.innerHTML=''});var cover=root.querySelector('#coverBackdrop');if(cover)cover.removeAttribute('style');var drawer=root.querySelector('#editorDrawer');if(drawer){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')}var tour=root.querySelector('#tourOverlay');if(tour){tour.classList.remove('active');tour.setAttribute('aria-hidden','true')}var deck=root.querySelector('#deckOverlay');if(deck){deck.classList.remove('active');deck.setAttribute('aria-hidden','true')}var tray=root.querySelector('#curateTray');if(tray)tray.classList.remove('open','has-items');var cursor=root.querySelector('#smartCursor');if(cursor)cursor.classList.remove('active');var lb=root.querySelector('#lightbox');if(lb)lb.setAttribute('style','display:none');var cockpit=root.querySelector('.interaction-cockpit');if(cockpit)cockpit.classList.remove('visible');var search=root.querySelector('#searchInput');if(search)search.removeAttribute('value');slot.textContent=safeJson({version:2,embeddedAt:new Date().toISOString(),works:works});var stamp=new Date().toISOString().slice(0,10).replace(/-/g,''),html='<!DOCTYPE html>\n'+root.outerHTML;downloadTextFile('xiaokai-portfolio-'+stamp+'.html',html,'text/html;charset=utf-8');alert('已生成新版 HTML。新增作品已经写进文件，发给别人也能看到。')}

document.querySelectorAll('.scene-dot').forEach(function(d){d.addEventListener('click',function(){Array.prototype.slice.call(document.body.classList).forEach(function(cls){if(cls.indexOf('scene-')===0)document.body.classList.remove(cls)});var scene=d.dataset.scene==='default'?'':'scene-'+d.dataset.scene;if(scene)document.body.classList.add(scene);document.querySelectorAll('.scene-dot').forEach(function(a){a.classList.remove('active')});d.classList.add('active')})});
document.querySelectorAll('.nav-link').forEach(function(l){l.addEventListener('click',function(){var t=document.getElementById(l.dataset.target);if(t)t.scrollIntoView({behavior:'smooth'});document.querySelectorAll('.nav-link').forEach(function(a){a.classList.remove('active')});l.classList.add('active')})});
document.getElementById('searchInput').addEventListener('input',function(e){searchQ=e.target.value;renderGallery()});
document.querySelectorAll('.role-option').forEach(function(b){b.addEventListener('click',function(){applyRole(b.dataset.role)})});
document.querySelectorAll('[data-cockpit]').forEach(function(b){b.addEventListener('click',function(){var a=b.dataset.cockpit;if(a==='tour')startTour();if(a==='role')document.getElementById('roleLab').scrollIntoView({behavior:'smooth',block:'center'});if(a==='random')openRandomWork();if(a==='deck')openDeck();if(a==='edit')openEditor()})});
document.getElementById('tourPrev').addEventListener('click',function(){nextTour(-1)});
document.getElementById('tourNext').addEventListener('click',function(){nextTour(1)});
document.getElementById('tourClose').addEventListener('click',closeTour);
document.getElementById('deckPrev').addEventListener('click',function(){navDeck(-1)});
document.getElementById('deckNext').addEventListener('click',function(){navDeck(1)});
document.getElementById('deckClose').addEventListener('click',closeDeck);
document.getElementById('deckCloseInline').addEventListener('click',closeDeck);
document.getElementById('curateToggle').addEventListener('click',function(){document.getElementById('curateTray').classList.toggle('open')});
document.getElementById('curatePlay').addEventListener('click',openDeck);
document.getElementById('curateClear').addEventListener('click',function(){CURATED_IDS=[];saveCurated();renderCurateTray();renderGallery()});
document.getElementById('ownerEdit').addEventListener('click',openEditor);
document.getElementById('editorClose').addEventListener('click',closeEditor);
document.getElementById('editorAdd').addEventListener('click',addUserWork);
document.getElementById('editorBuildHtml').addEventListener('click',generateStandaloneHtml);
document.getElementById('editorExport').addEventListener('click',exportUserWorks);
document.getElementById('editorImport').addEventListener('change',function(e){if(e.target.files[0])importUserWorks(e.target.files[0]);e.target.value=''});
document.getElementById('editorClear').addEventListener('click',function(){if(confirm('确定清空通过编辑器新增的作品吗？')){var ids={};USER_WORKS.forEach(function(w){ids[w.id]=1});USER_WORKS=[];saveUserWorks();DATA.works=DATA.works.filter(function(w){return !ids[w.id]});refreshAll()}});
window.addEventListener('scroll',updateScrollMeter,{passive:true});
window.addEventListener('hashchange',function(){if(location.hash==='#edit'&&isOwnerMode())openEditor();if(location.hash==='#deck')openDeck()});
document.addEventListener('keydown',function(e){var typing=document.activeElement.tagName==='INPUT'||document.activeElement.tagName==='TEXTAREA';var deckOpen=document.getElementById('deckOverlay').classList.contains('active');if(e.key==='Escape'){closeLB();closeTour();closeEditor();closeDeck()}if(!typing&&isOwnerMode()&&e.key.toLowerCase()==='e'&&!e.metaKey&&!e.ctrlKey)openEditor();if(!typing&&e.key.toLowerCase()==='p'&&!e.metaKey&&!e.ctrlKey)openDeck();if(deckOpen){if(e.key==='ArrowLeft')navDeck(-1);if(e.key==='ArrowRight')navDeck(1);return}if(document.getElementById('lightbox').style.display==='flex'){if(e.key==='ArrowLeft')navLB(-1);if(e.key==='ArrowRight')navLB(1)}});
document.getElementById('lightbox').addEventListener('click',function(e){if(e.target===document.getElementById('lightbox'))closeLB()});
document.getElementById('deckOverlay').addEventListener('click',function(e){if(e.target===document.getElementById('deckOverlay'))closeDeck()});

(function(){var c=document.getElementById('coverCanvas'),x=c.getContext('2d'),W,H,P,mx=-9999,my=-9999;function resize(){W=c.width=c.offsetWidth;H=c.height=c.offsetHeight}
function mkPt(){return{x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.3,vy:(Math.random()-.5)*.3,r:Math.random()*2+.5,a:Math.random()*.5+.1,ps:Math.random()*.02+.005,pp:Math.random()*Math.PI*2}}
function init(){resize();P=[];var n=Math.min(Math.floor(W*H/5000),250);for(var i=0;i<n;i++)P.push(mkPt())}
var fr=0;function loop(){x.clearRect(0,0,W,H);fr++;var cs=getComputedStyle(document.documentElement).getPropertyValue('--accent').trim();
for(var i=0;i<P.length;i++){var p=P[i];var dx=mx-p.x,dy=my-p.y,d=Math.sqrt(dx*dx+dy*dy);if(d<200){var f=(200-d)/200*.015;p.vx+=dx*f*.1;p.vy+=dy*f*.1}p.vx*=.98;p.vy*=.98;p.x+=p.vx;p.y+=p.vy;if(p.x<-20)p.x=W+20;if(p.x>W+20)p.x=-20;if(p.y<-20)p.y=H+20;if(p.y>H+20)p.y=-20;p.a=.15+Math.sin(fr*p.ps+p.pp)*.15;
x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fillStyle=cs;x.globalAlpha=p.a;x.fill();x.globalAlpha=1}
if(fr%3===0)for(var i=0;i<P.length;i++)for(var j=i+1;j<P.length;j++){var dx=P[i].x-P[j].x,dy=P[i].y-P[j].y,d=Math.sqrt(dx*dx+dy*dy);if(d<100){x.beginPath();x.moveTo(P[i].x,P[i].y);x.lineTo(P[j].x,P[j].y);x.strokeStyle=cs;x.globalAlpha=(1-d/100)*.08;x.lineWidth=.5;x.stroke();x.globalAlpha=1}}
requestAnimationFrame(loop)}
c.addEventListener('mousemove',function(e){var r=c.getBoundingClientRect();mx=e.clientX-r.left;my=e.clientY-r.top});c.addEventListener('mouseleave',function(){mx=my=-9999});
c.addEventListener('touchmove',function(e){var r=c.getBoundingClientRect(),t=e.touches[0];mx=t.clientX-r.left;my=t.clientY-r.top},{passive:true});c.addEventListener('touchend',function(){mx=my=-9999});
window.addEventListener('resize',function(){resize();init()});init();loop()})();

if(isOwnerMode())document.body.classList.add('owner-mode');loadUserWorks();loadCurated();renderHeroPreview();renderMetrics();renderCaseRail();renderCaseStories();renderCategoryStories();renderCatNav();renderGallery();bindPortfolioSwitch();bindContactActions();updateRoleUI();updateScrollMeter();wireTilt();renderEditor();renderCurateTray();initSmartCursor();initPortfolioMotion();if(isOwnerMode()&&location.hash==='#edit')openEditor();if(location.hash==='#deck')openDeck();

function revealHashTarget(){if(!location.hash)return;var target=document.querySelector(location.hash);if(!target)return;target.querySelectorAll('.motion-reveal').forEach(function(el){el.classList.add('is-visible')})}
setTimeout(revealHashTarget,900);
